### ISSUE TITLE
basic example gives error ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the UpdateFunctionConfiguration operation: Function not found: arn:aws:lambda:eu-west-1...

### ISSUE THREAD

**Issue by xor007** [aws-quickstart/quickstart-kubernetes-resource-provider#19]
Hi for me,

The basic example:

`
Resources:
 ExampleCm:
   Type: "AWSQS::Kubernetes::Resource"
   Properties:
     ClusterName: xxxeksprivatecluster
     Namespace: default
     Manifest: | 
       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: example-cm
       data:
         example_key: example_value

`

 give an error in eu-west-1

Exception caught An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: SubnetIds and SecurityIds must coexist or be both empty list.
Traceback (most recent call last):
  File "/var/task/awsqs_kubernetes_resource/vpc.py", line 116, in put_function
    no_update = update_function_config(lmbd, function_config)
  File "/var/task/awsqs_kubernetes_resource/vpc.py", line 131, in update_function_config
    lmbd.update_function_configuration(**function_config)
  File "/var/task/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the UpdateFunctionConfiguration operation: Function not found: arn:aws:lambda:eu-west-1:...redacted...:function:awsqs-kubernetes-resource-proxy-frgeksprivatecluster

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 219, in __call__
    raise error
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 212, in __call__
    progress = self._invoke_handler(caller_sess, request, action, callback)
  File "/var/task/cloudformation_cli_python_lib/resource.py", line 92, in _invoke_handler
    progress = handler(session, request, callback_context)
  File "/var/task/awsqs_kubernetes_resource/handlers.py", line 148, in delete_handler
    if not get_model(model, session):
  File "/var/task/awsqs_kubernetes_resource/utils.py", line 222, in get_model
    outp = run_command(cmd, cluster, session)
  File "/var/task/awsqs_kubernetes_resource/utils.py", line 53, in run_command
    put_function(session, cluster_name)
  File "/var/task/awsqs_kubernetes_resource/vpc.py", line 121, in put_function
    lmbd.create_function(Code={"ZipFile": zip_file.read()}, **function_config)
  File "/var/task/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: SubnetIds and SecurityIds must coexist or be both empty list.

**Comment by xor007** [comment]
My cluster is private that is why it failed. There needs to be an update to documentation to mention that that the cluster needs a public endpoint for this Resource provider to wokr
